[project]
name = "python-selenium-news"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "autopep8==2.3.2",
    "matplotlib==3.10.8",
    "pandas==3.0.1",
    "pylint==4.0.4",
    "selenium==4.40.0",
    "tabulate==0.9.0",
]
